### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by bendichter**

### CODE REVIEW

**Review by oruebel — APPROVED** [review]

**Comment by bendichter** [comment]
@oruebel thanks for the review. I do not have merge privileges in this org

**Comment by oruebel** [comment]
@bendichter I merged the PR. If you need privileges for this org then please ping Ryan so he can add you.

**Comment by bendichter** [comment]
attn @rly

**Comment by rly** [comment]
@bendichter I just gave you owner privileges for the org which should grant you all powers.

**Pull request merged**
